# Generated by Django 5.1.1 on 2024-10-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="zipcode",
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
