# Generated by Django 5.1.1 on 2024-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="store_zipcode",
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="zipcode",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="store_desc",
            field=models.TextField(unique=True),
        ),
    ]
