# Generated by Django 5.1.1 on 2024-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_vendor_store_zipcode_alter_user_zipcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="store_slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
