# Generated by Django 5.1.1 on 2024-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_vendor_store_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vendor",
            new_name="Store",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
