# Generated by Django 5.1.1 on 2024-10-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_vendor_store_alter_user_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_vendor",
            new_name="email_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="has_store",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
